/** @type {import('tailwindcss').Config} */

export default {
	darkMode: ['class'],
	content: [
		'./src/pages/**/*.{js,ts,jsx,tsx,mdx}',
		'./src/components/**/*.{js,ts,jsx,tsx,mdx}',
		'./src/app/_components/*.{js,ts,jsx,tsx,mdx}',
		'./src/app/_components/ui/*.{js,ts,jsx,tsx,mdx}',
		'./src/app/**/*.{js,ts,jsx,tsx,mdx}',
	],
	theme: {
		extend: {
			colors: {
				background: 'hsl(var(--background))',
				foreground: 'hsl(var(--foreground))',
				card: {
					DEFAULT: 'hsl(var(--card))',
					foreground: 'hsl(var(--card-foreground))',
				},
				popover: {
					DEFAULT: 'hsl(var(--popover))',
					foreground: 'hsl(var(--popover-foreground))',
				},
				primary: {
					DEFAULT: 'hsl(var(--primary))',
					foreground: 'hsl(var(--primary-foreground))',
				},
				secondary: {
					DEFAULT: 'hsl(var(--secondary))',
					foreground: 'hsl(var(--secondary-foreground))',
				},
				muted: {
					DEFAULT: 'hsl(var(--muted))',
					foreground: 'hsl(var(--muted-foreground))',
				},
				accent: {
					DEFAULT: 'hsl(var(--accent))',
					foreground: 'hsl(var(--accent-foreground))',
				},
				destructive: {
					DEFAULT: 'hsl(var(--destructive))',
					foreground: 'hsl(var(--destructive-foreground))',
				},
				border: 'hsl(var(--border))',
				input: 'hsl(var(--input))',
				ring: 'hsl(var(--ring))',
				chart: {
					'1': 'hsl(var(--chart-1))',
					'2': 'hsl(var(--chart-2))',
					'3': 'hsl(var(--chart-3))',
					'4': 'hsl(var(--chart-4))',
					'5': 'hsl(var(--chart-5))',
					'6': 'hsl(var(--chart-6))',
					'7': 'hsl(var(--chart-7))',
					'8': 'hsl(var(--chart-8))',
					'9': 'hsl(var(--chart-9))',
					'10': 'hsl(var(--chart-10))',
					'11': 'hsl(var(--chart-11))',
					'12': 'hsl(var(--chart-12))',
					'13': 'hsl(var(--chart-13))',
					'14': 'hsl(var(--chart-14))',
					'15': 'hsl(var(--chart-15))',
					active: 'hsl(var(--chart-active))',
					debug: 'hsl(var(--chart-debug))',
					idle: 'hsl(var(--chart-idle))',
				},
				//* TODO: MAtch these to VSC Language Identifiers
				lang: {
					javascript: 'hsl(var(--lang-javascript))',
					python: 'hsl(var(--lang-python))',
					java: 'hsl(var(--lang-java))',
					csharp: 'hsl(var(--lang-csharp))',
					cpp: 'hsl(var(--lang-cpp))',
					typescript: 'hsl(var(--lang-typescript))',
					ruby: 'hsl(var(--lang-ruby))',
					go: 'hsl(var(--lang-go))',
					rust: 'hsl(var(--lang-rust))',
					abap: 'hsl(var(--lang-abap))',
					bat: 'hsl(var(--lang-bat))',
					bibtex: 'hsl(var(--lang-bibtex))',
					clojure: 'hsl(var(--lang-clojure))',
					coffeescript: 'hsl(var(--lang-coffeescript))',
					c: 'hsl(var(--lang-c))',
					dockercompose: 'hsl(var(--lang-dockercompose))',
					css: 'hsl(var(--lang-css))',
					'cuda-cpp': 'hsl(var(--lang-cuda-cpp))',
					d: 'hsl(var(--lang-d))',
					dart: 'hsl(var(--lang-dart))',
					pascal: 'hsl(var(--lang-pascal))',
					diff: 'hsl(var(--lang-diff))',
					dockerfile: 'hsl(var(--lang-dockerfile))',
					erlang: 'hsl(var(--lang-erlang))',
					fsharp: 'hsl(var(--lang-fsharp))',
					'git-commit': 'hsl(var(--lang-git-commit))',
					'git-rebase': 'hsl(var(--lang-git-rebase))',
					groovy: 'hsl(var(--lang-groovy))',
					handlebars: 'hsl(var(--lang-handlebars))',
					haml: 'hsl(var(--lang-haml))',
					haskell: 'hsl(var(--lang-haskell))',
					html: 'hsl(var(--lang-html))',
					ini: 'hsl(var(--lang-ini))',
					javascriptreact: 'hsl(var(--lang-javascriptreact))',
					json: 'hsl(var(--lang-json))',
					jsonc: 'hsl(var(--lang-jsonc))',
					julia: 'hsl(var(--lang-julia))',
					latex: 'hsl(var(--lang-latex))',
					less: 'hsl(var(--lang-less))',
					lua: 'hsl(var(--lang-lua))',
					makefile: 'hsl(var(--lang-makefile))',
					markdown: 'hsl(var(--lang-markdown))',
					'objective-c': 'hsl(var(--lang-objective-c))',
					'objective-cpp': 'hsl(var(--lang-objective-cpp))',
					ocaml: 'hsl(var(--lang-ocaml))',
					perl: 'hsl(var(--lang-perl))',
					php: 'hsl(var(--lang-php))',
					plaintext: 'hsl(var(--lang-plaintext))',
					powershell: 'hsl(var(--lang-powershell))',
					pug: 'hsl(var(--lang-pug))',
					r: 'hsl(var(--lang-r))',
					razor: 'hsl(var(--lang-razor))',
					scss: 'hsl(var(--lang-scss))',
					shaderlab: 'hsl(var(--lang-shaderlab))',
					shellscript: 'hsl(var(--lang-shellscript))',
					slim: 'hsl(var(--lang-slim))',
					sql: 'hsl(var(--lang-sql))',
					stylus: 'hsl(var(--lang-stylus))',
					svelte: 'hsl(var(--lang-svelte))',
					swift: 'hsl(var(--lang-swift))',
					typescriptreact: 'hsl(var(--lang-typescriptreact))',
					tex: 'hsl(var(--lang-tex))',
					vb: 'hsl(var(--lang-vb))',
					vue: 'hsl(var(--lang-vue))',
					'vue-html': 'hsl(var(--lang-vue-html))',
					xml: 'hsl(var(--lang-xml))',
					xsl: 'hsl(var(--lang-xsl))',
					yaml: 'hsl(var(--lang-yaml))',
				},
				framework: {
					react: 'hsl(var(--framework-react))',
					vue: 'hsl(var(--framework-vue))',
					angular: 'hsl(var(--framework-angular))',
					svelte: 'hsl(var(--framework-svelte))',
					solid: 'hsl(var(--framework-solid))',
					qwik: 'hsl(var(--framework-qwik))',
					lit: 'hsl(var(--framework-lit))',
					astro: 'hsl(var(--framework-astro))',
					nextjs: 'hsl(var(--framework-nextjs))',
					nuxt: 'hsl(var(--framework-nuxt))',
					gatsby: 'hsl(var(--framework-gatsby))',
					remix: 'hsl(var(--framework-remix))',
					nodejs: 'hsl(var(--framework-nodejs))',
					deno: 'hsl(var(--framework-deno))',
					bun: 'hsl(var(--framework-bun))',
				},
				tool: {
					docker: 'hsl(var(--tool-docker))',
					kubernetes: 'hsl(var(--tool-kubernetes))',
					terraform: 'hsl(var(--tool-terraform))',
					ansible: 'hsl(var(--tool-ansible))',
					jenkins: 'hsl(var(--tool-jenkins))',
					git: 'hsl(var(--tool-git))',
					github: 'hsl(var(--tool-github))',
					gitlab: 'hsl(var(--tool-gitlab))',
					nginx: 'hsl(var(--tool-nginx))',
					apache: 'hsl(var(--tool-apache))',
				},
				cloud: {
					aws: 'hsl(var(--cloud-aws))',
					azure: 'hsl(var(--cloud-azure))',
					gcp: 'hsl(var(--cloud-gcp))',
					digitalocean: 'hsl(var(--cloud-digitalocean))',
					heroku: 'hsl(var(--cloud-heroku))',
					vercel: 'hsl(var(--cloud-vercel))',
					netlify: 'hsl(var(--cloud-netlify))',
				},
				db: {
					mysql: 'hsl(var(--db-mysql))',
					postgresql: 'hsl(var(--db-postgresql))',
					mongodb: 'hsl(var(--db-mongodb))',
					redis: 'hsl(var(--db-redis))',
					sqlite: 'hsl(var(--db-sqlite))',
					cassandra: 'hsl(var(--db-cassandra))',
					neo4j: 'hsl(var(--db-neo4j))',
					elasticsearch: 'hsl(var(--db-elasticsearch))',
					dynamodb: 'hsl(var(--db-dynamodb))',
					supabase: 'hsl(var(--db-supabase))',
					firebase: 'hsl(var(--db-firebase))',
				},
			},
			borderRadius: {
				lg: 'var(--radius)',
				md: 'calc(var(--radius) - 2px)',
				sm: 'calc(var(--radius) - 4px)',
			},
			keyframes: {
				'accordion-down': {
					from: {
						height: '0px',
					},
					to: {
						height: 'var(--radix-accordion-content-height)',
					},
				},
				'accordion-up': {
					from: {
						height: 'var(--radix-accordion-content-height)',
					},
					to: {
						height: '0px',
					},
				},
			},
			animation: {
				'accordion-down': 'accordion-down 0.2s ease-out',
				'accordion-up': 'accordion-up 0.2s ease-out',
			},
		},
	},
	plugins: [require('tailwindcss-animate')],
} satisfies Config;
